### PR TITLE
Working dir for a receipt

### PR DESCRIPTION
**Pull request by ghost**
In some cases, it's desirable for a container to use working dir defined in Docker image metadata.

However, the current code always sets working dir to the current directory, thus overriding the value of working dir.

To address this situation and to maintain backward compatibility with existing clients, it seems reasonable to introduce additional fields to the structures Receipt and Config correspondingly.

Proposed changes would allow a client to explicitly decide whether to use working dir defined in image metadata or the current directory.

Although this solution might not be ideal in terms of client expectations, it could be considered as an intermediate one without breaking API changes.

### CODE REVIEW

**Comment by ghost** [comment]
@elemir could you please review suggested changes?

**Comment by elemir** [comment]
@mlosev, good idea

**Comment by ghost** [comment]
@elemir could you please make a patch release, so that a new version could be picked by the `dep` tool automatically?

**Comment by elemir** [comment]
@mlosev, I'm sorry. I'm thinking about another things now, so I forgot tagging.

**Pull request merged**
